# Permalinks
permalink:        pretty

# Setup
url:              http://nishantsh.github.io/

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Nishant Sharma

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
   Hello I am Nishant Sharma, A hard core android developer.


# The tags listed as entries in the sidebar
sidebar_tags:     []

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nishant.jpg
color:            '#A85641'

author:
  name:           'Nishant Sharma'
  twitter:        
  github:         nishantsh
  photo:          http://nishantsh.github.io/public/img/nishant.jpg
  email:          nishant@headerlabs.com

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
   About section is comming soon.....
